name: Deploy Grafana to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Замените на ваш регион

    - name: Verify AWS credentials
      run: |
        if aws sts get-caller-identity > /dev/null 2>&1; then
          echo "AWS credentials configured successfully"
        else
          echo "Failed to configure AWS credentials" >&2
          exit 1
        fi

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.22.0

    - name: Install kubectl and verify access
      run: |
        if aws eks update-kubeconfig --region us-east-1 --name YOUR_EKS_CLUSTER_NAME; then
          echo "Kubeconfig updated successfully"
        else
          echo "Failed to update kubeconfig" >&2
          exit 1
        fi

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.6.3

    - name: Deploy Grafana from local chart
      run: |
        helm install grafana ./grafana/charts --namespace monitoring --create-namespace --set adminPassword=YOUR_ADMIN_PASSWORD