name: Deploy Prometheus to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBECTL_VERSION: v1.22.0
      HELM_VERSION: v3.6.3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: ${{ env.KUBECTL_VERSION }}

    - name: Install kubectl and verify access
      run: |
        if aws eks update-kubeconfig --region us-east-1 --name ilya_Cluster; then
          echo "Kubeconfig updated successfully"
        else
          echo "Failed to update kubeconfig" >&2
          exit 1
        fi

    - name: Wait for cluster to be ready
      run: |
        kubectl wait --for=condition=Ready nodes --all --timeout=300s

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Add and update Prometheus Helm repository
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update || { echo "Failed to update Helm repo" >&2; exit 1; }

    - name: Uninstall existing Prometheus release
      run: |
        helm uninstall prometheus || echo "No previous Prometheus release found"

    - name: Deploy Prometheus from official repo
      run: |
        helm install prometheus prometheus-community/prometheus

    - name: Verify Prometheus deployment
      run: |
        kubectl rollout status deployment/prometheus-server -n default || { echo "Prometheus server deployment failed" >&2; exit 1; }