name: Deploy Prometheus to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'prometheus/charts/prometheus/**'
      - 'prometheus/charts/alertmanager/**'
      - 'prometheus/charts/kube-state-metrics/**'
      - 'prometheus/charts/prometheus-node-exporter/**'
      - 'prometheus/charts/prometheus-pushgateway/**'
      # Добавьте другие директории, если необходимо

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.22.0

    - name: Install kubectl and verify access
      run: |
        if aws eks update-kubeconfig --region us-east-1 --name ilya_Cluster; then
          echo "Kubeconfig updated successfully"
        else
          echo "Failed to update kubeconfig" >&2
          exit 1
        fi

    - name: Verify Kubernetes access
      run: |
        if kubectl get nodes > /dev/null 2>&1; then
          echo "Kubernetes cluster is accessible"
        else
          echo "Failed to access Kubernetes cluster" >&2
          exit 1
        fi

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.6.3

    - name: Update Helm dependencies
      run: |
        helm dependency update ./prometheus/charts/prometheus

    - name: Deploy Prometheus from local chart
      run: |
        helm upgrade --install prometheus ./prometheus/charts/prometheus --namespace monitoring --create-namespace




