name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      selected_workflow:
        description: 'Select the pipeline to run'
        required: true
        default: 'deploy-prometheus'
        type: choice
        options:
          - deploy-prometheus
          - deploy-grafana
          - deploy-eks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables based on selected environment
      run: |
        if [ "${{ github.event.inputs.environment }}" == "production" ]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ secrets.STAGING_CLUSTER_NAME }}" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ secrets.DEV_CLUSTER_NAME }}" >> $GITHUB_ENV
        fi

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Authenticate GitHub CLI
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

    - name: Run selected workflow
      run: |
        if [ "${{ github.event.inputs.selected_workflow }}" == "deploy-prometheus" ]; then
          echo "Running Deploy Prometheus workflow"
          gh workflow run deploy-prometheus.yml
        elif [ "${{ github.event.inputs.selected_workflow }}" == "deploy-grafana" ]; then
          echo "Running Deploy Grafana workflow"
          gh workflow run deploy-grafana.yml
        elif [ "${{ github.event.inputs.selected_workflow }}" == "deploy-eks" ]; then
          echo "Running Deploy EKS workflow"
          # Здесь добавьте команду для деплоя вашего EKS кластера, если она у вас есть.
        else
          echo "No matching workflow found"
        fi