name: Deploy to Minikube

on:
  workflow_dispatch:
    inputs:
      selected_workflow:
        description: 'Select the deployment'
        required: true
        default: 'deploy-prometheus'
        type: choice
        options:
          - deploy-prometheus
          - deploy-grafana

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup kubectl for Minikube
      run: |
        # Создание директории для kubeconfig
        mkdir -p $HOME/.kube

        # Настройка доступа к локальному Minikube с использованием IPv6
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        kubectl config set-cluster minikube --server=https://99.56.14.113:8089 --insecure-skip-tls-verify=true
        kubectl config set-context minikube
        kubectl config use-context minikube

    - name: Verify Minikube Authentication
      run: |
        echo "Verifying Minikube connection..."
        kubectl --server=https://99.56.14.113:8089 --insecure-skip-tls-verify get nodes

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install GitHub CLI (for Prometheus deployment)
      if: ${{ github.event.inputs.selected_workflow == 'deploy-prometheus' }}
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Authenticate GitHub CLI (for Prometheus deployment)
      if: ${{ github.event.inputs.selected_workflow == 'deploy-prometheus' }}
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

    - name: Deploy Grafana using Helm
      if: ${{ github.event.inputs.selected_workflow == 'deploy-grafana' }}
      run: |
        helm upgrade --install grafana ./grafana/charts/grafana \
        --namespace monitoring --create-namespace \
        --set adminPassword=${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    - name: Run selected Prometheus workflow
      if: ${{ github.event.inputs.selected_workflow == 'deploy-prometheus' }}
      run: |
        gh workflow run deploy-prometheus.yml --log