name: Deploy to Minikube

on:
  workflow_dispatch:
    inputs:
      selected_workflow:
        description: 'Select the deployment'
        required: true
        default: 'deploy-prometheus'
        type: choice
        options:
          - deploy-prometheus
          - deploy-grafana

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup kubectl for Minikube
      run: |
        # Создание директории для kubeconfig
        mkdir -p $HOME/.kube

        # Настройка доступа к локальному Minikube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
        kubectl config set-cluster minikube --server=http://104.28.104.103:8080 --insecure-skip-tls-verify=true
        kubectl config set-context minikube
        kubectl config use-context minikube

    - name: Verify Minikube Authentication
      run: |
        echo "Verifying Minikube connection..."
        kubectl get nodes

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Authenticate GitHub CLI
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

    - name: Run selected workflow
      run: |
        if [ "${{ github.event.inputs.selected_workflow }}" == "deploy-prometheus" ]; then
          echo "Running Deploy Prometheus workflow"
          gh workflow run deploy-prometheus.yml
        elif [ "${{ github.event.inputs.selected_workflow }}" == "deploy-grafana" ]; then
          echo "Running Deploy Grafana workflow"
          gh workflow run deploy-grafana.yml
        else
          echo "No matching workflow found"
        fi